name: easy_autocomplete
description: A simple but flexible autocomplete TextFormField to help you display suggestions to your users while typing
version: 1.6.0
homepage: https://github.com/4inka/flutter_easy_autocomplete

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
